# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=x86_64-unknown-linux-gnu
#
# Metadata:
# - nixpkgs revision: 82b583ba2ba2e5706b35dbe23f31362e62be2a9d
# - hydra build: https://hydra.nixos.org/job/nixpkgs/trunk/stdenvBootstrapTools.x86_64-unknown-linux-gnu.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/249165517
# - instantiated derivation: /nix/store/7g8mrv13mi4zrx66fw0hy4c46j752wfd-stdenv-bootstrap-tools.drv
# - output directory: /nix/store/dw6vr6m5w7ysrdrbs0s5wdgbjmbnr7gx-stdenv-bootstrap-tools
# - build time: Sat, 10 Feb 2024 01:29:55 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "https://git.mjones.io/mike/bootstrap-scripts/releases/download/0.1.0/bootstrap-tools.tar.xz";
    hash = "sha256-lIj991pq5DHW45B1yAZ2BE34yx1HYrW0Cno+G3eyalM=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "https://git.mjones.io/mike/bootstrap-scripts/releases/download/0.1.0/busybox";
    hash = "sha256-5RJvO8XtNML4rGRX/TW4LUbp46PoDcYCRXreWJK5eeg=";
    executable = true;
  };
}
