{
  lib,
  fetchurl,
  bash,
  buildPlatform,
  coreutils,
  diffutils,
  gcc,
  musl,
  binutils,
  gnumake,
  gnupatch,
  gnutar,
  bzip2,
  findutils,
  gnused,
  grep,
  gawk,
  m4,
  perl,
  autoconf,
  automake,
  automake15,
  libtool,
  flex,
  bison,
  gmp,
  mpfr,
  mpc,
  zlib,
}:
let
  pname = "gcc";
  version = "4.7.4";
  target = "${buildPlatform.parsed.cpu.name}-${buildPlatform.parsed.kernel.name}-musl";

  src = fetchurl {
    url = "https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.bz2";
    hash = "sha256-kuYcbcOgpEnmLXKjgYX9pVAWioZwLeoHEl69PsOZYoI=";
  };
in
bash.runCommand "${pname}-${version}"
  {
    inherit pname version;

    nativeBuildInputs = [
      coreutils
      diffutils
      gcc
      musl
      binutils
      gnumake
      gnupatch
      gnutar
      bzip2
      findutils
      gnused
      grep
      gawk
      m4
      perl
      autoconf
      automake
      automake15
      libtool
      flex
      bison
      gmp
      mpfr
      mpc
      zlib
    ];

    meta = {
      description = "GNU Compiler Collection";
      homepage = "https://gcc.gnu.org/";
      license = lib.licenses.gpl3Plus;
      teams = [ lib.teams.minimal-bootstrap ];
      platforms = lib.platforms.unix;
      mainProgram = "gcc";
    };
  }
  ''
    # Unpack
    cp ${src} gcc.tar.bz2
    ${bzip2}/bin/bzip2 -d -f gcc.tar.bz2
    ${gnutar}/bin/tar xf gcc.tar
    rm gcc.tar

    for patch in ${./4.7.4/patches}/*.patch; do
      ${gnupatch}/bin/patch -Np0 -i "$patch"
    done

    cd gcc-${version}
    cp ${./4.7.4/files/decDPD.h.preamble} decDPD.h.preamble
    cp ${./4.7.4/files/decDPD_generate.c} decDPD_generate.c

    cat > gcc-for-build <<EOF_INNER
    #!${bash}/bin/bash
    exec ${gcc}/bin/gcc \
      -isystem ${musl}/include \
      -B ${musl}/lib \
      -L ${musl}/lib \
      "\$@"
    EOF_INNER
    chmod 555 gcc-for-build

    cat > cc <<EOF_INNER
    #!${bash}/bin/bash
    exec "''${PWD}/gcc-for-build" "\$@"
    EOF_INNER
    chmod 555 cc
    export PATH="''${PWD}:$PATH"

    # Prepare
    ${findutils}/bin/find . -type f -exec ${grep}/bin/grep -l '^#! */bin/sh' {} + | while IFS= read -r script; do
      ${gnused}/bin/sed -i "1s|^#! */bin/sh\\(.*\\)$|#! ${bash}/bin/bash\\1|" "$script"
      chmod +x "$script"
    done

    ${gnused}/bin/sed -i "s|#!/bin/sh|#! ${bash}/bin/bash|g" gcc/genmultilib

    rm gcc/cp/cfns.h

    rm configure Makefile.in fixincludes/fixincl.x

    rm libgo/aclocal.m4 libgo/configure libgo/Makefile.in
    rm gcc/config/avr/t-multilib
    rm gcc/config/mep/intrinsics.h gcc/config/mep/intrinsics.md \
      gcc/config/mep/mep-intrin.h
    rm gcc/config/arm/arm_neon.h
    rm gcc/testsuite/gcc.target/x86_64/abi/test_passing_integers.c \
      gcc/testsuite/gcc.target/x86_64/abi/test_3_element_struct_and_unions.c \
      gcc/testsuite/gcc.target/x86_64/abi/test_passing_floats.c \
      gcc/testsuite/gcc.target/x86_64/abi/test_basic_returning.c
    rm gcc/testsuite/go.test/test/bench/go1/jsondata_test.go \
      gcc/testsuite/go.test/test/bench/shootout/mandelbrot.txt
    rm gcc/testsuite/go.test/test/cmplxdivide1.go
    ${findutils}/bin/find zlib -name "*.obj" -delete
    rm zlib/contrib/puff/zeros.raw zlib/contrib/blast/test.pk \
      zlib/contrib/dotzlib/DotZLib.chm
    ${findutils}/bin/find libjava -name "*.class" -delete
    ${findutils}/bin/find libjava -type f -name "*.jar" -delete
    ${findutils}/bin/find libjava -name "*.h" -exec ${grep}/bin/grep -l "DO NOT EDIT THIS FILE" {} \; | ${findutils}/bin/xargs rm
    rm libjava/classpath/gnu/java/lang/CharData.java \
      libjava/classpath/gnu/java/rmi/dgc/DGCImpl_Skel.java \
      libjava/classpath/gnu/java/rmi/dgc/DGCImpl_Stub.java \
      libjava/classpath/gnu/java/rmi/registry/RegistryImpl_Skel.java \
      libjava/classpath/gnu/java/rmi/registry/RegistryImpl_Stub.java
    rm libjava/classpath/resource/gnu/java/locale/*.properties \
      libjava/classpath/resource/java/text/*.properties \
      libjava/classpath/resource/java/util/*.properties
    rm libjava/include/java-chardecomp.h \
      libjava/include/java-chartables.h
    rm -r libjava/testsuite/libjava.cni \
      libjava/testsuite/libjava.jvmti
    rm boehm-gc/MacProjects.sit.hqx
    ${findutils}/bin/find fixincludes/tests -name "*.h" -delete
    ${findutils}/bin/find . -name "*.pdf" -delete
    rm -r libstdc++-v3/doc/html
    rm libgfortran/generated/*.F90
    rm -r libgo/go/debug/elf/testdata \
      libgo/go/debug/macho/testdata \
      libgo/go/debug/pe/testdata \
      libgo/go/debug/dwarf/testdata
    rm libgo/go/regexp/syntax/perl_groups.go
    rm libgo/go/strconv/isprint.go

    rm libjava/sources.am libjava/Makefile.in

    rm libgcc/config/sh/lib1funcs.S libgcc/config/sh/lib1funcs-4-300.S
    rm libjava/classpath/java/util/TimeZone.java
    rm libjava/gcj/javaprims.h

    rm boehm-gc/cord/de_win.ICO
    export ACLOCAL_PATH="${libtool}/share/aclocal:${automake}/share/aclocal-1.11"

    for dir in intl libcpp libdecnumber; do
      (
        cd "$dir"
        rm aclocal.m4
        AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 aclocal-1.11 --acdir=../config
      )
    done

    (
      cd gcc
      rm aclocal.m4
      AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 aclocal-1.11 --acdir=../config
    )

    (
      cd fixincludes
      rm aclocal.m4
      AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 aclocal-1.11 --acdir=../gcc
    )

    for dir in boehm-gc libffi libgfortran libgomp libitm libjava libmudflap libobjc libquadmath libssp lto-plugin zlib libjava/classpath libjava/libltdl; do
      (
        cd "$dir"
        rm aclocal.m4
        AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 aclocal-1.11
      )
    done

    (
      cd libstdc++-v3
      ACLOCAL=aclocal-1.11 AUTOMAKE=automake-1.11 AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 autoreconf-2.64 -fi
    )

    for dir in $(${findutils}/bin/find . -mindepth 2 -maxdepth 2 -name configure.ac | ${gnused}/bin/sed 's#/configure.ac##' | ${grep}/bin/grep -v -x -e './libgo' -e './boehm-gc' | tr "\n" " " | ${gnused}/bin/sed -e 's/ $/\n/'); do
      (
        cd "$dir"
        rm configure
        autoconf-2.64 || autoconf-2.64
      )
    done

    for dir in $(${findutils}/bin/find . -mindepth 2 -maxdepth 2 -name Makefile.am | ${gnused}/bin/sed 's#/Makefile.am##' | ${grep}/bin/grep -v -x -e './libgo' -e './libjava' -e './boehm-gc' | tr "\n" " " | ${gnused}/bin/sed -e 's/ $/\n/'); do
      (
        cd "$dir"
        rm Makefile.in
        AUTOCONF=autoconf-2.64 AUTOM4TE=autom4te-2.64 automake-1.11 --add-missing
      )
    done

    for dir in libdecnumber libcpp libiberty gcc; do
      (
        cd "$dir"
        rm -f config.in
        autoheader-2.64
      )
    done

    (
      cd libiberty
      CC=cc ${bash}/bin/bash ./configure --enable-maintainer-mode
      ${gnumake}/bin/make maint-deps
    )

    rm config.guess config.sub ltmain.sh
    rm libjava/libltdl/missing
    libtoolize -i
    rm config.sub
    cp ${automake15}/share/automake-1.15/config.sub .
    for dir in libjava/libltdl libjava/classpath libgo/config; do
      (
        cd "$dir"
        libtoolize -i
      )
    done

    rm intl/plural.c

    rm gcc/gengtype-lex.c

    (
      cd libiberty
      ${gnused}/bin/sed -n '/^   #include <stdio.h>/,/^   \}$/p' crc32.c > crcgen.c
      cc -o crcgen crcgen.c
      ${gnused}/bin/sed '/crc_v3\.txt/{n; q}' crc32.c > crc32.c.new
      ./crcgen >> crc32.c.new
      ${gnused}/bin/sed '1,/^};$/d' crc32.c >> crc32.c.new
      mv crc32.c.new crc32.c
    )

    rm libdecnumber/decDPD.h
    cc -std=c99 -o decDPD_generate decDPD_generate.c
    cp decDPD.h.preamble libdecnumber/decDPD.h
    chmod u+w libdecnumber/decDPD.h
    ./decDPD_generate >> libdecnumber/decDPD.h

    ${findutils}/bin/find . -name '*.gmo' -delete

    rm libiberty/functions.texi
    ${findutils}/bin/find . -name '*.info' -delete

    ${findutils}/bin/find . -name '*.[1-9]' -delete

    # Configure
    mkdir build
    cd build

    for dir in libiberty libcpp libdecnumber gcc libgcc libstdc++-v3; do
      mkdir "$dir"
      (
        cd "$dir"
        CC=cc \
          CPPFLAGS="-I${gmp}/include -I${mpfr}/include -I${mpc}/include -I${zlib}/include" \
          LDFLAGS="-L${gmp}/lib -L${mpfr}/lib -L${mpc}/lib -L${zlib}/lib" \
          ${bash}/bin/bash ../../$dir/configure \
            --prefix=''${out} \
            --libdir=''${out}/lib \
            --build=${target} \
            --target=${target} \
            --host=${target} \
            --disable-shared \
            --program-transform-name= \
            --enable-languages=c,c++ \
            --disable-sjlj-exceptions \
            --with-system-zlib \
            --with-gmp=${gmp} \
            --with-mpfr=${mpfr} \
            --with-mpc=${mpc}
      )
    done
    cd ..

    # Build
    ln -s . "build/build-${target}"
    for dir in libiberty libcpp libdecnumber gcc; do
      ${gnumake}/bin/make -j "$NIX_BUILD_CORES" -C build/$dir \
        LIBGCC2_INCLUDES=-I${musl}/include \
        STMP_FIXINC= \
        GMPLIBS="-L${mpc}/lib -lmpc -L${mpfr}/lib -lmpfr -L${gmp}/lib -lgmp" \
        MAKEINFO=true
    done

    ${gnumake}/bin/make -j "$NIX_BUILD_CORES" -C build/libgcc PATH="$PATH:../gcc" CC=../gcc/xgcc \
      host_subdir=build CFLAGS="-I../gcc/include -I${musl}/include"

    ${gnumake}/bin/make -j "$NIX_BUILD_CORES" -C build/libstdc++-v3 PATH="$PATH:$PWD/build/gcc" \
      CXXFLAGS="-I$PWD/build/gcc/include -I${musl}/include"

    # Install
    ${gnumake}/bin/make -C build/gcc install STMP_FIXINC= MAKEINFO=true
    ${gnumake}/bin/make -C build/libgcc install host_subdir=build
    ${gnumake}/bin/make -C build/libstdc++-v3 install
    ln -s gcc ''${out}/bin/cc

    mkdir -p ''${out}/lib/gcc/${target}/${version}/include
    cp gcc/gsyslimits.h ''${out}/lib/gcc/${target}/${version}/include/syslimits.h

    mkdir -p ''${out}/lib/gcc/${target}/${version}/include/
    mv ''${out}/lib/gcc/${target}/4.0.4/include/* ''${out}/lib/gcc/${target}/${version}/include/
    rmdir ''${out}/lib/gcc/${target}/4.0.4/include
    mv ''${out}/lib/gcc/${target}/4.0.4/* ''${out}/lib/gcc/${target}/${version}/
    # Strip debug symbols from toolchain artifacts to keep bootstrap outputs small.
    shopt -s nullglob globstar
    for f in ''${out}/bin/**/* ''${out}/lib/**/* ''${out}/libexec/**/*; do
      [ -f "$f" ] || continue
      if command -v strip >/dev/null 2>&1; then
        strip --strip-debug "$f" 2>/dev/null || true
      fi
      if command -v ${target}-strip >/dev/null 2>&1; then
        ${target}-strip --strip-debug "$f" 2>/dev/null || true
      fi
    done
  ''
